[package]
name = "whoisupthere"
version = "0.1.0"
authors = ["Robert Peters <r2p2.gw@gmail.com>"]

[dependencies]
clap = "2.31"
open-notify-api = { git = "https://github.com/r2p2/open-notify-api", branch = "master" }